### ISSUE TITLE
the code can not run correctly 

### ISSUE THREAD

**Issue by layshua** [FabST/WebGL-Fluid-Simulation#1]
i download the code and try to run,but failed, i use Firefox Nightly 75.0a1 (2020-02-21) (64-bit)  and 45.0a1 in windows 10, the "start simulation" button doesn't work. can the code run correctly on your pc?  thank you very much.

**Comment by FabianStoll** [comment]
Unfortunately I haven't touched this project in the last four years.
It used to work with the Firefox Nightly 45.0a1 Build on Windows 7 and was not tested on any browser or system newer than that.

**Comment by layshua** [comment]
ok, thank you, I will try again.
